package id.ac.poliban.mi.yusfan.listnegara;

import android.widget.ListView;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class CountryData {
    static List<Counrty> getAllContries(){

    List<Counrty> data = new ArrayList<>();

    {
        data.add(new Counrty("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/188px-Flag_of_Argentina.svg.png", "Argentina", "Argentina (Spanish: [aɾxenˈtina]), officially the Argentine Republic[A] (Spanish: República Argentina), is a country located mostly in the southern half of South America. Sharing the bulk of the Southern Cone with Chile to the west, the country is also bordered by Bolivia and Paraguay to the north, Brazil to the northeast, Uruguay and the South Atlantic Ocean to the east, and the Drake Passage to the south. With a mainland area of 2,780,400 km2 (1,073,500 sq mi),[B] Argentina is the eighth-largest country in the world, the fourth largest in the Americas, the second largest in South America after Brazil, and the largest Spanish-speaking nation. The sovereign state is subdivided into twenty-three provinces (Spanish: provincias, singular provincia) and one autonomous city (ciudad autónoma), Buenos Aires, which is the federal capital of the nation (Spanish: Capital Federal) as decided by Congress.[17] The provinces and the capital have their own constitutions, but exist under a federal system. Argentina claims sovereignty over part of Antarctica, the Falkland Islands (Spanish: Islas Malvinas), and South Georgia and the South Sandwich Islands."));
        data.add(new Counrty("https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/188px-Flag_of_Brazil.svg.png", "Brazil", "Brazil (Portuguese: Brasil; Portuguese pronunciation: [bɾaˈziw]),[nt 1] officially the Federative Republic of Brazil (Portuguese: República Federativa do Brasil, About this soundlisten (help·info)),[9] is the largest country in both South America and Latin America. At 8.5 million square kilometers (3.2 million square miles)[10] and with over 208 million people, Brazil is the world's fifth-largest country by area and the fifth most populous. Its capital is Brasília, and its most populated city is São Paulo. The federation is composed of the union of the 26 states, the Federal District, and the 5,570 municipalities. It is the largest country to have Portuguese as an official language and the only one in the Americas;[11][12] it is also one of the most multicultural and ethnically diverse nations, due to over a century of mass immigration from around the world."));
        data.add(new Counrty("https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/188px-Flag_of_Paraguay.svg.png","Paraguay","Paraguay (/ˈpærəɡwaɪ/; Spanish pronunciation: [paɾaˈɣwaj] (About this soundlisten); Guarani: Paraguái, [paɾaˈɰwaj]), officially the Republic of Paraguay (Spanish: República del Paraguay; Guarani: Tetã Paraguái), is a country in South America. It is bordered by Argentina to the south and southwest, Brazil to the east and northeast, and Bolivia to the northwest. Although it is one of only two landlocked countries in South America (the other is Bolivia), the country has coasts,[9] beaches[10] and ports on the Paraguay and Paraná rivers that give exit to the Atlantic Ocean through the Paraná-Paraguay Waterway.[11] Due to its central location in South America, it is sometimes referred to as Corazón de Sudamérica (\"Heart of South America\")."));
        data.add(new Counrty("https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/188px-Flag_of_Germany.svg.png", "Germany", "Germany (German: Deutschland, German pronunciation: [ˈdɔʏtʃlant]), officially the Federal Republic of Germany (German: Bundesrepublik Deutschland, About this soundlisten (help·info)),[g] is a country in Central and Western Europe, lying between the Baltic and North Seas to the north and the Alps, Lake Constance and the High Rhine to the south. It borders Denmark to the north, Poland and the Czech Republic to the east, Austria and Switzerland to the south, France to the southwest, and Luxembourg, Belgium and the Netherlands to the west. "));
        data.add(new Counrty("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/188px-Flag_of_Croatia.svg.png", "Croatia", "Croatia (/kroʊˈeɪʃə/ (About this soundlisten), kroh-AY-shə; Croatian: Hrvatska, pronounced [xř̩ʋaːtskaː]), officially the Republic of Croatia (Croatian: Republika Hrvatska, About this soundlisten (help·info)),[d] is a country at the crossroads of Central and Southeast Europe, on the Adriatic Sea. It borders Slovenia to the northwest, Hungary to the northeast, Serbia to the east, Bosnia and Herzegovina, and Montenegro to the southeast, sharing a maritime border with Italy. Its capital, Zagreb, forms one of the country's primary subdivisions, along with twenty counties. Croatia has an area of 56,594 square kilometres (21,851 square miles) and a population of 4.28 million, most of whom are Roman Catholics."));
    }
    return data;
    }
}
